# Setup
title:               Matthew Hirt
tagline:             'Missiologist'
description:         '<img src="/public/wax-seal.png" class="center">The personal website for Matthew Hirt'
url:                 https://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Matthew Hirt
  url:               https://twitter.com/matthewhirt
  email:             mhirt@sebts.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
